project:
  type: website
  output-dir: docs

book:
  title: "formosan-corpus-r"
  author: "Jane Doe"
  date: "22/11/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

