project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!Internal/"

website:
  title: "CHU0387"
  repo-url: https://github.com/aymeric-collart/CHU0387
  repo-actions: [issue]
  page-footer: 
    left: "© 2026 Aymeric Collart"
    right: 
      - text: "{{< iconify fa6-brands bluesky >}}"
        href: https://bsky.app/profile/aymericcollart.bsky.social
      - icon: github
        href: https://github.com/aymeric-collart
      - text: "This website is built with Quarto"

  # Top Navigation Bar
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Syllabus"
        href: syllabus.qmd
      - text: "Course"
        href: intro.qmd
      - text: "Assignments"
      - text: "More content"
        menu: 
          - More2.qmd
          - CorpusLiterature.qmd
    right:
      - icon: github
        href: https://github.com/aymeric-collart/CHU0387

  # Side Navigation Bar
  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    contents: 
      - section: "Introductory week"
        contents: 
          - intro.qmd
      - section: "Part 1: Principles of corpus studies"
        contents: 
          - Week2.qmd
          - Week3.qmd
      - section: "Part 2: Building a corpus from the internet with modern tools"
        contents: 
          - Week4.qmd
          - Week5.qmd
          - Week6.qmd
          - Weeks7_8.qmd
      - section: "Week 9: Group and individual meetings in the classroom"
      - section: "Week 10: Midterm presentations"      
      - section: "Part 3: Simple preprocessing and analyses of corpus data"
        contents: 
          - Week11.qmd
          - Week12.qmd
          - Week13.qmd
          - Week14.qmd
      - section: "Week 15: Group and individual meetings in the classroom"
      - section: "Week 16: Final presentations"



bibliography: references.bib

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    toc: true
    css: styles.css