project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!Internal/"

website:
  navbar:
    background: primary
    search: true
    left:
      - text: "Welcome page"
        href: index.qmd
      - text: "Get into the tutorial"
        href: intro.qmd
    right:
      - text: "Instructor"
        href: instructor.qmd
  sidebar:
    style: "floating"
    collapse-level: 1
    contents: 
    - text: "Introduction"
      href: intro.qmd
    - section: "Chapter 1. Getting Started"
      contents: 
        - InstallationRRStudio.qmd
        - RStudioInterface.qmd
        - WorkingWithRMarkdown.qmd
    - section: "Chapter 2. Let's get our data"
      contents: 
        - references.qmd
    - part: "Chapter 3. Cleaning and analyzing the data"
  page-footer: 
    left: "Copyright 2024, Aymeric Collart" 
    right: 
      - text: "{{< iconify fa6-brands bluesky >}}"
        href: https://bsky.app/profile/aymericcollart.bsky.social
      - icon: github
        href: https://github.com/aymeric-collart



bibliography: references.bib

format:
  html:
    theme: Lumen
  pdf:
    documentclass: scrreprt
  revealjs:
    progress: true
    theme: [simple, slides_footer.scss]

editor: visual

