project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!Internal/"

website:
  reader-mode: true
  navbar:
    background: primary
    search: true
    left:
      - text: "Welcome page"
        href: index.qmd
      - text: "Get into the course"
        href: intro.qmd
    right:
      - text: "Instructor"
        href: instructor.qmd
  sidebar:
    style: "floating"
    collapse-level: 1
    contents: 
    - text: "Week 1: Introduction"
      href: intro.qmd
    - text: "--------"
    - section: "Part 1: Principles of corpus studies"
      contents: 
        - Week2.qmd
        - Week3.qmd
    - text: "--------"
    - section: "Part 2: Building a corpus from the internet with modern tools"
      contents: 
        - Week4.qmd
        - Week5_1.qmd
        - Week5_2.qmd
        - Weeks6_7.qmd
    - text: "--------"
    - section: "Part 3: Simple preprocessing and analyzes of corpus data"
  page-footer: 
    left: "Copyright 2025, Aymeric Collart" 
    right: 
      - text: "{{< iconify fa6-brands bluesky >}}"
        href: https://bsky.app/profile/aymericcollart.bsky.social
      - icon: github
        href: https://github.com/aymeric-collart



bibliography: references.bib

format:
  html:
    theme: Lumen
  pdf:
    documentclass: scrreprt
  revealjs:
    progress: true
    theme: [simple, slides_footer.scss]

editor: visual

