project:
  type: website
  output-dir: docs

book:
  title: "formosan-corpus-r"
  author: "Aymeric Collart"
  date: "22/11/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Chapter 1. Getting Started"
      chapters: 
        - summary.qmd
    - part: "Chapter 2. Let's get our data"
      chapters: 
        - references.qmd
    - part: "Chapter 3. Cleaning and analyzing the data"
  page-footer: 
    left: "Copyright 2024, Aymeric Collart" 
    right: 
      - icon: github
        href: https://github.com/
      - icon: twitter 
        href: https://twitter.com/ 

website:
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

