---
title: "Welcome page"
sidebar: false
format: 
  html:
    output-file: index.html
---

#  {.unnumbered}

```{=html}
<style>
hr.rounded {
  border-top: 1px solid #E5E4E2;
  border-radius: 5px;
}
</style>
```

<hr class="rounded">

```{=html}
<p style="font-size:32px;
          text-align: center">
Welcome to the website of the course "Language, Society and Literature with Corpus and Modern Technology" (code: CHU03887)
</p>
```

::: callout-note
## Note

The website of the course has just been created. That's why it looks quite empty and some pages not at their right place.

Stay tuned for further developments!
:::

<hr class="rounded">

<br>

```{=html}
<p style="background-color:#eeeeee;
          color: #404040;
          border-left: solid #bcbcbc 4px;
          border-radius: 4px;
          padding:0.7em;
          font-size:24px">
<b> &nbsp; &#129504; &nbsp; Description and objectives of the course</b>
</p>
```

This course introduces the principles of corpus studies assisted by modern technology with an emphasis on hands-on practice, and how corpus data can be useful in understanding how language is used in the media or in the literature. The course is divided into three parts: (a) fundamental concepts and practices when working with a corpus, (b) the process of building a corpus from texts on the Internet with modern technology, and (c) the handling, analyses and visualization of the corpus data. By the end of the course, the students are expected to acquire the basic knowledge of working with a corpus and will obtain a first approach to programming languages.

```{=html}
<p style="background-color:#eeeeee;
          color: #404040;
          border-left: solid #bcbcbc 4px;
          border-radius: 4px;
          padding:0.7em;
          font-size:24px">
<b> &nbsp; &#129504; &nbsp; General information for the 2025 Fall class</b>
</p>
```

```{=html}
<p style="background-color:#eeeeee;
color: #404040;
border-left: solid #bcbcbc 4px;
border-radius: 4px;
padding:0.7em;
font-size:24px">
<b>FAQ</b>

</p>
```

### 1- Do I need any background?

You do not need any particular background.

This course will start with the very basics. If you are already familiar with coding and/or the RStudio interface, it will of course be easier for you.

### 2- Which public?

In addition to the students enrolled in the course, anyone interested in having a first hands-on experience can follow the content of the website.