<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Week 5: Introduction to R (2/2): Basic functions</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-532fce776c63c931076d5ce395638b42.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/iconify-2.1.0/iconify-icon.min.js"></script>
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Welcome page</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./intro.html" aria-current="page"> 
<span class="menu-text">Get into the course</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="./instructor.html"> 
<span class="menu-text">Instructor</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <a class="flex-grow-1 no-decor" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
          <h1 class="quarto-secondary-nav-title">Week 5: Introduction to R (2/2): Basic functions</h1>
        </a>     
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 1: Introduction</span></a>
  </div>
</li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Part 1: Principles of corpus studies</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Week2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 2: What is a corpus, and their role to understand language and literature</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Week3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 3: Types of corpora: Selecting or building a corpus?</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Part 2: Building a corpus from the internet with modern tools</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Week4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 4: Introduction to the modern tool R (1/2): Installation and first steps</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Week5_1.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Week 5: Introduction to R (2/2): Basic functions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Week5_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 5: Introduction to R (2/2): How to create reproducible data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Weeks6_7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Weeks 6 &amp; 7: Building a corpus from media platforms</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Weeks8_9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Weeks 8 &amp; 9: Building a corpus from literature sources</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Week 10: Midterm presentations</span></span>
  </li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Part 3: Simple preprocessing and analyzes of corpus data</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Weeks11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 11: Data preprocessing - Tidying data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Week12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 12: Data analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Week13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 13: Data visualization</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Weeks14.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 14: Presenting a corpus-based study</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Week 15: Group and individual meetings in the classroom</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Week 16: Final presentations</span></span>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#the-interface-of-rstudio" id="toc-the-interface-of-rstudio" class="nav-link active" data-scroll-target="#the-interface-of-rstudio"><span class="header-section-number">1</span> The interface of RStudio</a>
  <ul>
  <li><a href="#general-overview-of-the-interface-blocks-blocks-blocks-and-blocks" id="toc-general-overview-of-the-interface-blocks-blocks-blocks-and-blocks" class="nav-link" data-scroll-target="#general-overview-of-the-interface-blocks-blocks-blocks-and-blocks"><span class="header-section-number">1.1</span> General overview of the interface: Blocks, blocks, blocks and blocks</a></li>
  <li><a href="#the-computer-block" id="toc-the-computer-block" class="nav-link" data-scroll-target="#the-computer-block"><span class="header-section-number">1.2</span> The computer block</a></li>
  <li><a href="#the-variable-block" id="toc-the-variable-block" class="nav-link" data-scroll-target="#the-variable-block"><span class="header-section-number">1.3</span> The variable block</a></li>
  <li><a href="#the-console-block" id="toc-the-console-block" class="nav-link" data-scroll-target="#the-console-block"><span class="header-section-number">1.4</span> The console block</a></li>
  <li><a href="#the-script-block" id="toc-the-script-block" class="nav-link" data-scroll-target="#the-script-block"><span class="header-section-number">1.5</span> The script block</a></li>
  <li><a href="#exercise-play-with-your-blocks" id="toc-exercise-play-with-your-blocks" class="nav-link" data-scroll-target="#exercise-play-with-your-blocks"><span class="header-section-number">1.6</span> Exercise: Play with your blocks!</a></li>
  <li><a href="#bonus-more-about-the-script-block" id="toc-bonus-more-about-the-script-block" class="nav-link" data-scroll-target="#bonus-more-about-the-script-block"><span class="header-section-number">1.7</span> Bonus: More about the script block</a></li>
  </ul></li>
  <li><a href="#libraries" id="toc-libraries" class="nav-link" data-scroll-target="#libraries"><span class="header-section-number">2</span> Libraries</a>
  <ul>
  <li><a href="#what-is-the-concept-of-the-libraries" id="toc-what-is-the-concept-of-the-libraries" class="nav-link" data-scroll-target="#what-is-the-concept-of-the-libraries"><span class="header-section-number">2.1</span> What is the concept of the “libraries”?</a></li>
  <li><a href="#how-to-install-and-use-libraries" id="toc-how-to-install-and-use-libraries" class="nav-link" data-scroll-target="#how-to-install-and-use-libraries"><span class="header-section-number">2.2</span> How to install and use libraries?</a></li>
  </ul></li>
  <li><a href="#some-basic-elements-of-r-language" id="toc-some-basic-elements-of-r-language" class="nav-link" data-scroll-target="#some-basic-elements-of-r-language"><span class="header-section-number">3</span> Some basic elements of R language</a>
  <ul>
  <li><a href="#first-things-first-the-working-directory" id="toc-first-things-first-the-working-directory" class="nav-link" data-scroll-target="#first-things-first-the-working-directory"><span class="header-section-number">3.1</span> First things first: The ‘working directory’</a></li>
  <li><a href="#your-first-script-some-syntax-and-vocabulary-of-r" id="toc-your-first-script-some-syntax-and-vocabulary-of-r" class="nav-link" data-scroll-target="#your-first-script-some-syntax-and-vocabulary-of-r"><span class="header-section-number">3.2</span> Your first script: Some syntax and vocabulary of R</a>
  <ul class="collapse">
  <li><a href="#add-comments" id="toc-add-comments" class="nav-link" data-scroll-target="#add-comments"><span class="header-section-number">3.2.1</span> Add comments</a></li>
  <li><a href="#basic-calculations" id="toc-basic-calculations" class="nav-link" data-scroll-target="#basic-calculations"><span class="header-section-number">3.2.2</span> Basic calculations</a></li>
  <li><a href="#assigning-variables" id="toc-assigning-variables" class="nav-link" data-scroll-target="#assigning-variables"><span class="header-section-number">3.2.3</span> Assigning variables</a></li>
  <li><a href="#load-data-from-your-computer-to-r" id="toc-load-data-from-your-computer-to-r" class="nav-link" data-scroll-target="#load-data-from-your-computer-to-r"><span class="header-section-number">3.2.4</span> Load data from your computer to R</a></li>
  <li><a href="#data-description-and-summary" id="toc-data-description-and-summary" class="nav-link" data-scroll-target="#data-description-and-summary"><span class="header-section-number">3.2.5</span> Data description and summary</a></li>
  <li><a href="#transforming-the-data-add-delete-change" id="toc-transforming-the-data-add-delete-change" class="nav-link" data-scroll-target="#transforming-the-data-add-delete-change"><span class="header-section-number">3.2.6</span> Transforming the data: add, delete, change</a></li>
  <li><a href="#plotting-the-data" id="toc-plotting-the-data" class="nav-link" data-scroll-target="#plotting-the-data"><span class="header-section-number">3.2.7</span> Plotting the data</a></li>
  <li><a href="#save-data-from-r-to-your-computer" id="toc-save-data-from-r-to-your-computer" class="nav-link" data-scroll-target="#save-data-from-r-to-your-computer"><span class="header-section-number">3.2.8</span> Save data from R to your computer</a></li>
  <li><a href="#r-script-of-this-section" id="toc-r-script-of-this-section" class="nav-link" data-scroll-target="#r-script-of-this-section"><span class="header-section-number">3.2.9</span> R script of this section</a></li>
  </ul></li>
  <li><a href="#common-mistakes-or-how-to-save-a-lot-of-time" id="toc-common-mistakes-or-how-to-save-a-lot-of-time" class="nav-link" data-scroll-target="#common-mistakes-or-how-to-save-a-lot-of-time"><span class="header-section-number">3.3</span> Common mistakes, or how to save a lot of time</a>
  <ul class="collapse">
  <li><a href="#i-cant-load-the-data-from-my-computer" id="toc-i-cant-load-the-data-from-my-computer" class="nav-link" data-scroll-target="#i-cant-load-the-data-from-my-computer"><span class="header-section-number">3.3.1</span> I can’t load the data from my computer</a></li>
  <li><a href="#i-dont-have-any-error-message-but-my-code-wont-run" id="toc-i-dont-have-any-error-message-but-my-code-wont-run" class="nav-link" data-scroll-target="#i-dont-have-any-error-message-but-my-code-wont-run"><span class="header-section-number">3.3.2</span> I don’t have any error message, but my code won’t run</a></li>
  <li><a href="#variable-not-found-what-happened" id="toc-variable-not-found-what-happened" class="nav-link" data-scroll-target="#variable-not-found-what-happened"><span class="header-section-number">3.3.3</span> “Variable not found”, what happened?</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block">Week 5: Introduction to R (2/2): Basic functions</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<style>
hr.rounded {
  border-top: 1px solid #E5E4E2;
  border-radius: 5px;
}
</style>
<p>Now I assume that R and RStudio are correctly installed on your computer. You can start by opening RStudio. You will see a lot of things on your screen, many blocks, many menus, and it can be quite overwhelming. No worries! This is exactly what this section is about!</p>
<div class="callout callout-style-default callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Objectives
</div>
</div>
<div class="callout-body-container callout-body">
<p>In this section, you will learn more about the RStudio interface and get familiarized with it.<br><br> But this section is not only about presenting the interface! In addition to that, you will also get familiar with the very basics of R language.</p>
</div>
</div>
<section id="the-interface-of-rstudio" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> The interface of RStudio</h1>
<section id="general-overview-of-the-interface-blocks-blocks-blocks-and-blocks" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="general-overview-of-the-interface-blocks-blocks-blocks-and-blocks"><span class="header-section-number">1.1</span> General overview of the interface: Blocks, blocks, blocks and blocks</h2>
<p>You may see the following picture on your screen after opening RStudio:</p>
<hr class="rounded">
<p><img src="./assets/images/RStudio_FirstPage.png" class="img-fluid"></p>
<hr class="rounded">
<p>The best way to apprehend RStudio is to understand the interface as <strong>blocks</strong>, which are here for different purposes.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>When you open RStudio for the very first time, you should get something similar as in the image above, with three blocks in the same order. But it’s also possible that you have something else. If that’s the case, this is completely normal and this won’t affect anything for the following steps!</p>
</div>
</div>
<p>There are four main blocks, as in the following image. I give them unofficial names so that it will be easier to refer to them. There is one block that I call the ‘computer block’, a second one the ‘data block’, a third one the ‘script block’, and finally the last one, the ‘console block’.</p>
<hr class="rounded">
<p><img src="./assets/images/RStudio_4Blocks.png" class="img-fluid"></p>
<hr class="rounded">
<p>You may not be able to see the ‘script block’ on your computer for the moment, and again, this is completely normal! Just follow the steps below.</p>
</section>
<section id="the-computer-block" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="the-computer-block"><span class="header-section-number">1.2</span> The computer block</h2>
<p>The ‘computer block’ is the one on the bottom right side. I call it the ‘computer block’ but it’s actually much more than that, but let’s keep it simple for the moment. First, click on the Files button. You will see that there is a list of files and folders from your computer. This is actually the interface you can use to communicate and navigate directly with your computer!</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Again, look at all the options and play with them to understand what everything’s about:</strong></p>
<ol type="1">
<li><p>Click on the files. How do these open? In RStudio? Directly on your computer?</p></li>
<li><p>Try to go to other folders on your computer using the computer block. You’ll see there is no mystery, this is just like navigating on your own computer as you usually do!</p></li>
</ol>
</div>
</div>
</section>
<section id="the-variable-block" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="the-variable-block"><span class="header-section-number">1.3</span> The variable block</h2>
<p>The ‘variable block’ is the one on the top right side, as in the image below.</p>
<hr class="rounded">
<p><img src="./assets/images/VariableBlock_Raw.png" class="img-fluid"></p>
<hr class="rounded">
<p>Basically, the most important tab is the ‘environment’ one. This is where the variables we create when coding will be stocked. The term ‘variable’ can be quite abstract at the moment, so let’s just exemplify it with our first code. R can be used as a simple calculator. In the ‘console block’, just write the following code, end press ‘enter’:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="dv">4</span><span class="sc">+</span><span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Normally, you’ll see this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="dv">4</span><span class="sc">+</span><span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6</code></pre>
</div>
</div>
<p>And indeed, ‘4 + 2’ equals 6. Now, let’s play a game. You want to obtain the number 8, but you have to use ‘4 + 2’. One option is to add 2 one more time, and you will write the following code:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="dv">4</span><span class="sc">+</span><span class="dv">2</span><span class="sc">+</span><span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8</code></pre>
</div>
</div>
<p>The game may continue, and you will need to write even more. This is when the variables can be useful. Try the following code:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="dv">4</span><span class="sc">+</span><span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Unlike what you have seen before, nothing appears in the console anymore. But there is something new in the variable block:</p>
<hr class="rounded">
<p><img src="./assets/images/VariableBlock_WithVariable.png" class="img-fluid"></p>
<hr class="rounded">
<p>You stocked the calculation ‘4+2’ as a variable, and you can call it anytime you want! For example, you can call it by simply writing <code>a</code> in the console, and you can also add 2 to it by writing <code>a + 2</code>, and you’ll see something as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> a</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>[<span class="dv">1</span>] <span class="dv">6</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> a<span class="sc">+</span><span class="dv">2</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>[<span class="dv">1</span>] <span class="dv">8</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This example is just here to show what the ‘variables’ are. With just simple calculations like the ones above, it seems to be quite useless. But you’ll realize very quickly through this tutorial that variables are not only useful, but also necessary to handle more data.</p>
</section>
<section id="the-console-block" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="the-console-block"><span class="header-section-number">1.4</span> The console block</h2>
<p>Now let’s talk very briefly about the ‘console block’. You just had a glimpse of it when reading the section on the variable block. Actually, there’s not a lot more to say about it. <strong>The console block is the place where the code is written and being run.</strong></p>
<p>In addition to the ‘Console’ tab, there are also the ‘Terminal’ tab and the ‘Background Jobs’ tab. Despite their importance, we won’t have have to use them in this tutorial. So let’s just skip them!</p>
</section>
<section id="the-script-block" class="level2" data-number="1.5">
<h2 data-number="1.5" class="anchored" data-anchor-id="the-script-block"><span class="header-section-number">1.5</span> The script block</h2>
<p>The ‘script’ block is where you’ll work most of the time. You can see it as the Word or the Note Pad of RStudio. You will better understand the importance of the scripts, one more time, with an example. If you’ve followed Section 1.3, you can see that you have the same code as below in your console.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="dv">4</span><span class="sc">+</span><span class="dv">2</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>[<span class="dv">1</span>] <span class="dv">6</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> a <span class="ot">&lt;-</span> <span class="dv">4</span><span class="sc">+</span><span class="dv">2</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> a</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>[<span class="dv">1</span>] <span class="dv">6</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> a<span class="sc">+</span><span class="dv">2</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>[<span class="dv">1</span>] <span class="dv">8</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now, just close R and reopen it. All the codes disappeared! We usually use R for much more than a simple calculator, and we always end up with hundreds of lines of codes. Imagine if you need to rewrite everything each time you close and reopen R… and this is where the scripts are useful!</p>
<p>Let’s do a simple exercise with the script. First, open a new script by clicking on “New File”, and then the first option, called “R Script”.</p>
<hr class="rounded">
<p><img src="./assets/images/OpenNewScript.gif" class="img-fluid"></p>
<hr class="rounded">
<p>Write the lines below in the script block:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="dv">4</span><span class="sc">+</span><span class="dv">2</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="dv">4</span><span class="sc">+</span><span class="dv">2</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>a</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>a<span class="sc">+</span><span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>After that, select everything, and click on ‘Run’. You can also have a look at the short video below.</p>
<hr class="rounded">
<p><img src="./assets/images/Script_Demo.gif" class="img-fluid"></p>
<hr class="rounded">
<p>This is how you run a script! Alternatively, you can select everything (or just the line you interested in), and press ‘enter’ on your keyboard. Now you can save your script (“File &gt; Save”) and close R. Find the file you just saved on your computer and open it. Your code is still here!</p>
</section>
<section id="exercise-play-with-your-blocks" class="level2" data-number="1.6">
<h2 data-number="1.6" class="anchored" data-anchor-id="exercise-play-with-your-blocks"><span class="header-section-number">1.6</span> Exercise: Play with your blocks!</h2>
<p>Your four blocks are like construction toys you can play with. You can make them disappear and then reappear, you can change their size as you wish, and you can even change the background color. In other words, make RStudio your own!</p>
<p>This is how you can change the size of the blocks with your mouse:</p>
<hr class="rounded">
<p><img src="./assets/images/ChangeBlockSize.gif" class="img-fluid"></p>
<hr class="rounded">
<p>This is how you change the background color of RStudio:</p>
<pre><code>Path: Tools &gt; Global Options... &gt; Appearance &gt; Choose the theme you like in 'Editor theme'</code></pre>
<hr class="rounded">
<p><img src="./assets/images/ChangeColor.gif" class="img-fluid"></p>
<hr class="rounded">
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Anecdote
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>I personally change the sizes of the blocks dynamically, depending on the task I’m doing. For example, if I’m writing more complex lines of codes which could be confusing, I enlarge the script block to be sure I’m not missing any parenthesis or comma. When I’m drawing plots, I make the computer block bigger to visualize more clearly what I’m doing, and it helps me to know if I want to add or change anything on the plot.<br> Everyone’s experience is different, it just depends on what your preferences are. So, really, make it your own!</p>
</div>
</div>
</div>
</section>
<section id="bonus-more-about-the-script-block" class="level2" data-number="1.7">
<h2 data-number="1.7" class="anchored" data-anchor-id="bonus-more-about-the-script-block"><span class="header-section-number">1.7</span> Bonus: More about the script block</h2>
<p>As you opened a new script, you may have realized that you had the choice between many options, as below.</p>
<hr class="rounded">
<p><img src="./assets/images/ScriptTypes.png" class="img-fluid"></p>
<hr class="rounded">
<p>We only used the “R Script” type, but you can actually do much more depending on what you want to do in your project. For example, you have “Quarto Document” or “R Markdown” which are like “R Script”. The difference is that R Scripts only save your codes, while Quarto Documents or R Markdowns allows more options, and especially to render out in a PDF or markdown file. By doing so, we can share our code along with the output of the code in a beautiful way, which is very important for Open Science!</p>
<p>You’ll also remark that even if we are using R, it is actually possible to write with other programming languages, such as HTML or Python. While this is not the case for R Scripts, it is possible with other types of scripts. You can even design a whole website using R, and ask R to transfer your data online… This is indeed how I am designing the website of the tutorial!</p>
<p>Script files have many very useful options, so many that I decided to dedicate a whole section to it. Jump <a href="#" target="_blank">here (link provided later)</a> if you want to know more!</p>
</section>
</section>
<section id="libraries" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Libraries</h1>
<section id="what-is-the-concept-of-the-libraries" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="what-is-the-concept-of-the-libraries"><span class="header-section-number">2.1</span> What is the concept of the “libraries”?</h2>
<p>You can do many things with R. Among others:</p>
<ul>
<li>Basic calculations</li>
<li>Data manipulation</li>
<li>Draw figures or plots of your data</li>
<li>Create geographical maps</li>
<li>Run simple and advanced statistics (summaries, t-tests, ANOVA, LMR, GLMR, Bayesian statistics, etc.)</li>
<li>Design a whole website</li>
<li>Preprocess neuroimaging data (EEG, fMRI, etc.)</li>
<li>Download data from the web to be further manipulated</li>
<li>Create applications</li>
</ul>
<p>And many many other possibilities. You may have a sense of it, the more complex the task is, the more codes it requires. For example, it is not the same to calculate ‘2+4’ and putting statistical data on the map of Europe!</p>
<p>It can be overwhelming, and we can even have the feeling that quantitative research is not for us after all. <strong>Good news!</strong> We actually don’t need to write all the codes from scratch!</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
More on the nature of the R project
</div>
</div>
<div class="callout-body-container callout-body">
<p>R is free and open source, it is a collaborative concept. And this is very important to be aware of this: <strong>Nobody,</strong> <em>nobody</em><strong>, writes all the raw codes for each task in one script.</strong> Just like we read articles and books instead of doing all the research on the field when we want to know more about something, we can rely on other people’s work when writing codes. <br>People wrote, and more importantly, <strong>published</strong>, articles and books so that we can have access to more knowledge. <br>People wrote, and more importantly, <strong>shared online</strong>, lines and lines of codes and functions such that we can have access to them, use them, instead of rewriting everything.</p>
</div>
</div>
<p>We need to introduce some concepts now:</p>
<ul>
<li>Lines of codes</li>
<li>Functions</li>
<li>Packages/Libraries</li>
</ul>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Name</th>
<th>Concept</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Line of codes</td>
<td>Just the code you write in the script/console to perform something specific. They are usually the most simple.</td>
</tr>
<tr class="even">
<td>Function</td>
<td>Sometimes, you need more than one line of code to perform a task. You may even want to perform the exact same task several times, but with different data. Of course, you can just copy and paste the same code everytime, but you can also choose to simplify it into one line of code. This is what a function is: <strong>a cluster of lines of codes</strong></td>
</tr>
<tr class="odd">
<td>Library/Package</td>
<td>And very often, you’ll need to perform many tasks which require more than one function. You can choose to write all the functions by hand anytime you need them. Or you can just have them already loaded somewhere in R, such that you can refer to them later when you need them. This is what a library or package is: <strong>a cluster of functions</strong></td>
</tr>
</tbody>
</table>
<p>
There are many many packages available for free with R. You can find them <a href="https://cran.r-project.org/web/packages/available_packages_by_name.html" target="_blank" class="btn btn--primary">here</a>. And they are even more that are not directly available from the R website, but developped and distributed by other people (generally on Github). They always come with a logo, as below.
</p>
<hr class="rounded">
<p><img src="./assets/images/RPackages.jpg" class="img-fluid"></p>
<hr class="rounded">
<p>We will very often refer to some of them, such as “readxl” to import data from Excel, “ggplot2” to draw figures, “tidyr” and “dplyr” to manipulate data, etc.</p>
</section>
<section id="how-to-install-and-use-libraries" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="how-to-install-and-use-libraries"><span class="header-section-number">2.2</span> How to install and use libraries?</h2>
<p>Installing libraries is quite easy. You have two ways to do so:</p>
<ul>
<li><p><strong>Using the Computer block</strong></p>
<p>So far, we’ve only mentioned the Computer block as the block where you can browse the folders and open the files on your computer. This block actually has more functions. If you look at the tabs, you will remark that we’ve only talked about the “Files”.</p>
<p>Now we will turn to the “Packages” tab, as in the image below. What you need to do is to click on “Install”, you write and select the name of the library you want to install, and finally click on “Install”. That’s it!</p></li>
</ul>
<hr class="rounded">
<p><img src="./assets/images/ComputerBlockPackages.png" class="img-fluid"></p>
<hr class="rounded">
<p>Give R a couple of minutes while it’s downloading the data and installing on your computer.</p>
<ul>
<li><p>Using the Console block</p>
<p>Alternatively, you can download/install packages directly from the Console block. You just need to write one line of code:</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"[Name of the package you wish to install]"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>For instance, if you want to install the package ‘ggplot2’, which is used to draw figures, here is what you need to write:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"ggplot2"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You will remark that for installing the packages, you need to write the name of the package between quotation marks</p>
<p>Now that you have downloaded the packages you need, this does not mean that you can use the functions in the libraries right away. The packages are installed, but you need to “call” them, or to load them, such that they are ready to use. Note that no quotation marks are used with this function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>([Name of the package])</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Think about it
</div>
</div>
<div class="callout-body-container callout-body">
<p>Let’s keep the metaphor of the articles and books published by other people. You want to prepare a memorable dinner, and to do so you need to buy a book with recipies that you can’t find online. To do so, you go to the bookstore and buy this wonderful book. Back home, you just put it on your bookshelf. <strong>The step of buying the book and bringing it back home corresponds to the <em>‘install.packages()’</em></strong> step.</p>
<p>Does having the book at home mean that you just need to go to your kitchen and start cooking? Of course not! You need to have this book opened with you in the kitchen to follow the recipies! This is exactly what we are doing when we load the packages in the <strong><em>‘library()’</em></strong> step!</p>
</div>
</div>
</section>
</section>
<section id="some-basic-elements-of-r-language" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Some basic elements of R language</h1>
<p>This subsection will introduce some basic elements of R codes that cannot be avoided. I will introduce codes referred to as ‘R-based’, meaning that there is no need to install any additional packages.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Play around!
</div>
</div>
<div class="callout-body-container callout-body">
<p>While you’re going through the examples below, don’t hesitate to open an R script, copy and paste the codes, run them to see what happens. In addition, you can also modify the codes and try new things. You may run into errors, but that’s ok. From my experience, it is the best way to get used to the R interface.</p>
</div>
</div>
<section id="first-things-first-the-working-directory" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="first-things-first-the-working-directory"><span class="header-section-number">3.1</span> First things first: The ‘working directory’</h2>
<p>This is one of the most important step, and also something that I always (and everybody should) check before anything else. The ‘working directory’ refers to the folder in your computer R is looking into. While you can navigate in the folders of your computer using the Computer block, this does not mean that R remembers where you are. To do so, you have to tell R:</p>
<blockquote class="blockquote">
<p>This is <strong>THE</strong> folder where the files I will load are, <strong>THE</strong> folder where my script will be saved, <strong>THE</strong> folder where all my files will be saved</p>
</blockquote>
<p>This is what the ‘working directory’, it is <strong>THE</strong> folder. Now, how to set your working directory, <strong>THE</strong> folder?</p>
<ol type="1">
<li><p>Use the Computer block to navigate in your computer until you are in the folder you wish to work in,</p></li>
<li><p>Click on the small image of the wheel, and then click on “Save as Working Directory”</p></li>
</ol>
<hr class="rounded">
<p><img src="./assets/images/SetWorkingDirectory.gif" class="img-fluid"></p>
<hr class="rounded">
<p>And you are done! You will see that a line of code appeared in the Console block, actually setting the working directory.</p>
</section>
<section id="your-first-script-some-syntax-and-vocabulary-of-r" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="your-first-script-some-syntax-and-vocabulary-of-r"><span class="header-section-number">3.2</span> Your first script: Some syntax and vocabulary of R</h2>
<section id="add-comments" class="level3" data-number="3.2.1">
<h3 data-number="3.2.1" class="anchored" data-anchor-id="add-comments"><span class="header-section-number">3.2.1</span> Add comments</h3>
<p>A useful tip when writing R code is the possibility to add comments. I use it all the time such that I can annotate why I used this function, the size I want to print my figure, etc. Comments are marked with the hashtag sign “#”. See the example below.<br> Note that you can add as many hashtag signs as you want. I personally have the habit to use three hashtag signs, but you could also just use one.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>    <span class="do">### This is a line of comment. I won't be run in the console, even if it is copied there.</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>    <span class="dv">2</span><span class="sc">+</span><span class="dv">4</span> <span class="do">### We can also add comments after a code. In that case, it will only run the code at the beginning of the line, and ignore everything after the # sign</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6</code></pre>
</div>
</div>
<p>Now that you know how to add comments in the script you have opened, just comment every line, even the ones that you created yourself!</p>
</section>
<section id="basic-calculations" class="level3" data-number="3.2.2">
<h3 data-number="3.2.2" class="anchored" data-anchor-id="basic-calculations"><span class="header-section-number">3.2.2</span> Basic calculations</h3>
<p>We have already referred to basic calculations in the previous subsections. These so-called basic calculations can even be complex, as below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span> <span class="sc">+</span> <span class="dv">343</span> <span class="sc">*</span> <span class="dv">34</span> <span class="sc">/</span> (<span class="dv">5</span> <span class="sc">-</span> <span class="dv">342</span> <span class="sc">+</span> <span class="dv">45</span> <span class="sc">*</span> <span class="dv">36</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11.08963</code></pre>
</div>
</div>
</section>
<section id="assigning-variables" class="level3" data-number="3.2.3">
<h3 data-number="3.2.3" class="anchored" data-anchor-id="assigning-variables"><span class="header-section-number">3.2.3</span> Assigning variables</h3>
<p>We have also already mentioned how to assign variables in previous subsections. Let’s recall it below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="dv">4</span><span class="sc">+</span><span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Another way to assign variables is by using the equal sign “=”. You just obtain the same results. I prefer using “&lt;-” because I find it visually more salient, but it depends on one’s preference.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>a <span class="ot">=</span> <span class="dv">4</span><span class="sc">+</span><span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You can also assign strings of letters. For example, you can try to add “This is my first script” to the variable “b”.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> This is my first script</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You will remark that… it didn’t work! You surely had the following message:</p>
<pre><code>Error: unexpected symbol in "b &lt;- This is"</code></pre>
<p>This is “This is my first script” has never been defined in R. In other words, R does not know what you are talking about! If you want to add strings of words, you need to use the quotation marks, as below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="st">"This is my first script"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You can also assign tables, datasets, plots, etc. You can even assign variables to variables. Try this below:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> a</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>What happened here? You had a variable called ‘a’, which had the value “6”. You also had the variable called ‘b’, which had the value “This is my first script”. In the above line of code, you are asking R to assign the value of the variable a to b… in other words, the value of ‘b’ becomes the same as ‘a’!</p>
</section>
<section id="load-data-from-your-computer-to-r" class="level3" data-number="3.2.4">
<h3 data-number="3.2.4" class="anchored" data-anchor-id="load-data-from-your-computer-to-r"><span class="header-section-number">3.2.4</span> Load data from your computer to R</h3>
<p>You may have already collected data, and you want to import your dataset into R. For this section, let’s use the data from the survey of “Great American Coffee Taste Test”. You can download the file <a href="https://github.com/aymeric-collart/CHU0387/blob/main/assets/files/GACTT_RESULTS_ANONYMIZED_v2.csv" target="_blank">here</a>. (source of the data: <a href="https://mavenanalytics.io/data-playground" target="_blank">https://mavenanalytics.io/data-playground</a>)</p>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Caution
</div>
</div>
<div class="callout-body-container callout-body">
<p>Don’t forget to place this file in the folder you are working in, and to set this folder as your working directory!</p>
</div>
</div>
<p>Now you have two ways to import the data into R:</p>
<ol type="1">
<li><p>with a line of code, or</p></li>
<li><p>with the R interface.</p></li>
</ol>
<p>Let’s first do it with the code below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"/Users/aymeric/Documents/GithubWebsites/CHU03887/assets/files/GACTT_RESULTS_ANONYMIZED_v2.csv"</span>, <span class="at">header=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now let’s decompose this:</p>
<ul>
<li><p><strong>read.csv()</strong>. This is the function which is used to import the file, which is a CSV file.</p></li>
<li><p>There are two elements inside the function, which are seperated with a comma:</p>
<ul>
<li><p><strong>“~/assets/files/GACTT_RESULTS_ANONYMIZED_v2.csv”</strong>. This is the path to access to the file, as well as the full name of the file</p></li>
<li><p><strong>header=TRUE</strong>. This means the first line of the table corresponds to the titles of the columns (you can try and change to “header = FALSE” to see what happens!).</p></li>
</ul></li>
<li><p>Finally, the dataset is assigned to the variable called “<strong>data</strong>”.</p></li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Think about it
</div>
</div>
<div class="callout-body-container callout-body">
<p>Why do we need to assign the data to a variable? As I always say, computers are very powerful and very stupid at the same time: they are here to do in a very short amount of time exactly what you tell them to do. In other words, if you only use the “read.csv()” function, it will only read the data, and forget it, that’s it!</p>
<p>But what we want to do actually is to read the data and save them into R, such that we can do further manipulations. This is why we need to “save” them using variables!</p>
</div>
</div>
<p>The second way is to use the R interface. To do so, check you Variable block. You have a tab called “Import Dataset”. Just click on it, and then “From Text (base)…”. A new window will open, and you just have to choose the file you want to import.</p>
<p>Now you have a new window where you are asked to set the options to import the file:</p>
<ul>
<li><p>You can change the name of the variable it will be assigned to. By default, it is the name of the file. Try to change to “data”.</p></li>
<li><p>You can also set the option that the first line corresponds to the names or labels of the columns. Where you see “Heading”, click on “Yes”.</p></li>
<li><p>And finally, you can click on “Import”.</p></li>
</ul>
<hr class="rounded">
<p><img src="./assets/images/ImportDataBaseR.gif" class="img-fluid"></p>
<hr class="rounded">
<p>And you are done, now you have a whole dataset ready for manipulation in R!</p>
</section>
<section id="data-description-and-summary" class="level3" data-number="3.2.5">
<h3 data-number="3.2.5" class="anchored" data-anchor-id="data-description-and-summary"><span class="header-section-number">3.2.5</span> Data description and summary</h3>
<p>I assume here that the dataset we just imported is still present in your environment. Now we will learn quick ways to describe and summarize the data we have.</p>
<p>The first step is to understand the structure of the dataset. This can be easily done with the ‘str()’ function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You will obtain the following results. For clarity, I only give the first four lines here.</p>
<pre><code>'data.frame':   4042 obs. of  111 variables:
 $ Submission.ID  : chr  "gMR29l" "BkPN0e" "W5G8jj" "4xWgGr" ...
 $ What.is.your.age.  : chr  "18-24 years old" "25-34 years old" "25-34 years old" "35-44 years old" ...
 $ How.many.cups.of.coffee.do.you.typically.drink.per.day.   : chr  "" "" "" "" ...
 $ Where.do.you.typically.drink.coffee.  : chr  "" "" "" "" ...</code></pre>
<p>This is how to read the data:</p>
<ul>
<li>The first line indicates the nature of the dataset. This is a “data frame”, with 4042 rows and 111 columns. Afterwards, the str() function describes these 111 columns.</li>
<li>The first column is called “Submission.ID”. The rows consist of strings of characters, and the str() function shows the data of the first four lines.</li>
<li>The second column is labelled “What.is.your.age.”, and again it consists of rows of strings of characters.</li>
<li>The same logic applies for all the lines.</li>
</ul>
<p>You will remark that we are facing a problem. In this survey, the participants were asked their age, and then their results were annotated as “18-24 years old”, “25-34 years old”, etc. In other words, there are <strong>groups of age</strong>, but when the data were imported, R considered them as strings of characters. Now we need to tell R that there are groups. This is done with the “as.factor()” function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>What.is.your.age. <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(data<span class="sc">$</span>What.is.your.age.)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now let’s decompose this line:</p>
<ul>
<li>In the as.factor() function, we told R the date from which column needed to be transformed into groups. We now that this is the column called “What.is.your.age.” in the dataset called “data”. In R language, we write as follows: <i>data<strong>$</strong>What.is.your.age.</i>. The dollar sign is here to translate “inside of”</li>
<li>If we just write this part, R will only transform this column as a group, but it will not save it. So we need to save this operation in a variable, and as we want to replace the column considered as strings of characters, we do not have to create a new variable: we just use this column!</li>
</ul>
<p>Actually, the same problem occurs for the two following columns:</p>
<ol type="1">
<li><p>How.many.cups.of.coffee.do.you.typically.drink.per.day., and</p></li>
<li><p>Where.do.you.typically.drink.coffee.</p></li>
</ol>
<p>So we need to do the same changes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>How.many.cups.of.coffee.do.you.typically.drink.per.day. <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(data<span class="sc">$</span>How.many.cups.of.coffee.do.you.typically.drink.per.day.)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>Where.do.you.typically.drink.coffee. <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(data<span class="sc">$</span>Where.do.you.typically.drink.coffee.)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>And now let’s run the str() function again. Here are the results of the first four lines:</p>
<pre><code>'data.frame':   4042 obs. of  111 variables:
 $ Submission.ID  : chr  "gMR29l" "BkPN0e" "W5G8jj" "4xWgGr" ...
 $ What.is.your.age. : Factor w/ 8 levels "","&lt;18 years old",..: 4 5 5 6 5 8 4 1 5 1 ...
 $ How.many.cups.of.coffee.do.you.typically.drink.per.day. : Factor w/ 7 levels "","1","2","3",..: 1 1 1 1 1 1 1 1 6 1 ...
 $ Where.do.you.typically.drink.coffee. : Factor w/ 66 levels "","At a cafe",..: 1 1 1 1 1 1 10 1 2 1 ...</code></pre>
<p>This is much more informative! For instance, this is telling us that there are 8 groups of age (in R, these are called “levels”). But maybe we would like to know the number of people per group among the 4042 participants. This can be done with the summary() function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This is what you obtain in the Console block:</p>
<hr class="rounded">
<p><img src="./assets/images/ExampleSummaryFunction.png" class="img-fluid"></p>
<hr class="rounded">
<p>How to read this? It is telling us that there are 1986 respondents in the “25-34 years old” group, 960 in the “35-44 years old” group, etc. Also that there are 1277 people drinking 1 cup of coffee per day, 1663 people 2 cups of coffee per day, etc.</p>
</section>
<section id="transforming-the-data-add-delete-change" class="level3" data-number="3.2.6">
<h3 data-number="3.2.6" class="anchored" data-anchor-id="transforming-the-data-add-delete-change"><span class="header-section-number">3.2.6</span> Transforming the data: add, delete, change</h3>
<p>Transforming the data is the task we spend the most of out time when doing the research. This can be tedious, but it is crucial to plot the right data and to conduct the right analyses. It is also very important to be aware of what we are doing when transforming the data. The aim is to make them more easily readable for R.</p>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Caution
</div>
</div>
<div class="callout-body-container callout-body">
<p>Data transformation or data manipulation does not mean new data creation or data selection!<br> We make changes to highlight some results, we select for ease of clarity, but such changes and selections are actually transformations and selection of <strong>the form</strong>, not the content!</p>
</div>
</div>
<p>You are actually already familiar with data transformation. In the previous section we have changed the class of the data of three columns: strings of characters to factors. I will exemplify here other changes we can make, but the list is not exhaustive at all.</p>
<p>You have surely remarked that there are many columns in the dataset we loaded. Generally, we collect more than we need, in case that in the end, we may need these data. But sometimes, having very large datasets can make us quite confused when trying to read and interpret the data. Therefore, sometimes, we would like a dataset with only the comumns we need.<br> For instance, we have talked of three columns so far in the previous section. We want to select them, in addition to the column indicating the ID of the respondents. We can do so with the code below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>data2 <span class="ot">&lt;-</span> data[,<span class="fu">c</span>(<span class="st">"Submission.ID"</span>,</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"What.is.your.age."</span>,</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"How.many.cups.of.coffee.do.you.typically.drink.per.day."</span>,</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"Where.do.you.typically.drink.coffee."</span>)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Again, let’s decompose this:</p>
<ul>
<li>The dataset from which we want to select data is called ‘data’. We select data from it by adding brackets, therefore “data[ ]”.</li>
<li>The columns are selected by adding a comma first (there are reasons for this, but it is not important for our purpose now), and then adding the name of the column. For example, we may have written “data[,”Submission.ID”]“, and this selects the columns called ‘Submission.ID’.</li>
<li>But we want to select more than one column. Unfortunately, we cannot write the names of all the columns directly. We need to inform R first that there is a list of columns. We use “c()” to do so.</li>
<li>Finally, we save this into a variable. We may have saved this to “data” (i.e.&nbsp;“data &lt;- data[….]”), but when doing so, we would have overwritten our original data. And if in the end, we realize that we need other columns, we have to redo everything! This is why it is good to have the habit to save into other variables when performing transformations of this kind.</li>
</ul>
<p>Now we will learn another trick: How to check which groups we have. In other words, how many groups of age are there in the data we have? This can be done as below:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(data2<span class="sc">$</span>What.is.your.age.)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] ""                "&lt;18 years old"   "&gt;65 years old"   "18-24 years old"
[5] "25-34 years old" "35-44 years old" "45-54 years old" "55-64 years old"</code></pre>
</div>
</div>
<p>We use the level() function, and we inform R which columns we want to look at inside the parentheses. We obtain the results as above.</p>
<p>There are 8 groups, but the first one corresponds to people who did not reply. We would like to remove this in order to have a full dataset. If we do not want to do it with other libraries, we can do it as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>data2 <span class="ot">&lt;-</span> <span class="fu">subset</span>(data2, What.is.your.age. <span class="sc">!=</span> <span class="st">""</span>)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>data2<span class="sc">$</span>What.is.your.age. <span class="ot">&lt;-</span> <span class="fu">droplevels</span>(data2<span class="sc">$</span>What.is.your.age.)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>In the first line, we are telling R to remove the rows where the group is ““.
<ul>
<li>To do so, we use the subset() function. In the parentheses, we set the parameters to tell R which rows to remove: dataset name (“data2”), column (“What.is.your.age.”), level (““).</li>
<li>Note that we used the sign “!=”. This signs means “remove”. If we change this sign to “==”, it means “select”!</li>
</ul></li>
<li>We only removed the rows corresponding to ““, but not the label. This is the purpose of the second line.</li>
</ul>
<p>Now you can run the “levels(data2$What.is.your.age.)” again. You will see that the level “” has indeed been removed!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(data2<span class="sc">$</span>What.is.your.age.)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "&lt;18 years old"   "&gt;65 years old"   "18-24 years old" "25-34 years old"
[5] "35-44 years old" "45-54 years old" "55-64 years old"</code></pre>
</div>
</div>
<p>If we look at the column called “How.many.cups.of.coffee.do.you.typically.drink.per.day.”, there is the same problem. We just have to run the same codes to solve this!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>data2 <span class="ot">&lt;-</span> <span class="fu">subset</span>(data2, How.many.cups.of.coffee.do.you.typically.drink.per.day. <span class="sc">!=</span> <span class="st">""</span>)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>data2<span class="sc">$</span>How.many.cups.of.coffee.do.you.typically.drink.per.day. <span class="ot">&lt;-</span> <span class="fu">droplevels</span>(data2<span class="sc">$</span>How.many.cups.of.coffee.do.you.typically.drink.per.day.)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now we would like to summarize the number of observations per group. And I will have to make an exception to what I said earlier: We are using the package called “dplyr”. So you will need to download it beforehand.</p>
<p>Here is the code you need to write:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>data3 <span class="ot">&lt;-</span> data2 <span class="sc">%&gt;%</span> </span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(What.is.your.age., How.many.cups.of.coffee.do.you.typically.drink.per.day.) <span class="sc">%&gt;%</span> </span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">Count =</span> <span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s decompose this:</p>
<ul>
<li>In the first line, we just loaded the library we need.</li>
<li>The sign “%&gt;%” is here to say we are going to run the codes below it based on the dataset called “data2”</li>
<li>The “group_by()” function is here to tell R which columns we will take into consideration. Notice that we do not need to write “data2$What.is.your.age.” since we used the “%&gt;%” sign.</li>
<li>Finally, the last line of code is the transformation we are performing: We want to summarize the data. Inside the “summarize()” function, we need to give the details of what we want to do (notice that you can also write “summarise()”!).
<ul>
<li>The “n()” function means that we just want to count the number of observations per group,</li>
<li>And the observations will be found in the “Count” column. Note that you can replace “Count” by any name you want!</li>
</ul></li>
<li>And finally, we store this summary table into a new variable, which we call “data3”.</li>
</ul>
<p>You should obtain something like this in the picture below:</p>
<hr class="rounded">
<p><img src="./assets/images/ResultsSummarize.png" class="img-fluid"></p>
<hr class="rounded">
<p>There are of course many more ways to transform the data, summarize them, etc. This subsection was only a snapshot of what is possible to do with a very minimum number of lines of codes!</p>
</section>
<section id="plotting-the-data" class="level3" data-number="3.2.7">
<h3 data-number="3.2.7" class="anchored" data-anchor-id="plotting-the-data"><span class="header-section-number">3.2.7</span> Plotting the data</h3>
<p>Now that we have summarized data, we can plot to see what they look like. We will use a very straightforward function, called… “plot()”! Let’s see what it does with the codes below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x =</span> data3<span class="sc">$</span>How.many.cups.of.coffee.do.you.typically.drink.per.day., <span class="at">y =</span> data3<span class="sc">$</span>Count)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week5_1_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x =</span> data3<span class="sc">$</span>What.is.your.age., <span class="at">y =</span> data3<span class="sc">$</span>Count)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week5_1_files/figure-html/unnamed-chunk-29-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We ran into a very superficial problem: R sorted the groups in alphabetical order, which is not quite straightforward! So we will need to reorder the levels before. Let’s do it with the code below:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>data3<span class="sc">$</span>What.is.your.age. <span class="ot">&lt;-</span> <span class="fu">factor</span>(data3<span class="sc">$</span>What.is.your.age., <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"&lt;18 years old"</span>,</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"18-24 years old"</span>,</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"25-34 years old"</span>,</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"35-44 years old"</span>,</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"45-54 years old"</span>,</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"55-64 years old"</span>,</span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"&gt;65 years old"</span>))</span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>data3<span class="sc">$</span>How.many.cups.of.coffee.do.you.typically.drink.per.day. <span class="ot">&lt;-</span> <span class="fu">factor</span>(data3<span class="sc">$</span>How.many.cups.of.coffee.do.you.typically.drink.per.day., <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Less than 1"</span>,</span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>         <span class="st">"1"</span>,</span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>         <span class="st">"2"</span>,</span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a>         <span class="st">"3"</span>,</span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a>         <span class="st">"4"</span>,</span>
<span id="cb41-14"><a href="#cb41-14" aria-hidden="true" tabindex="-1"></a>         <span class="st">"More than 4"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You can check whether this worked by using the “levels()” function we introduced above.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(data3<span class="sc">$</span>What.is.your.age.)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "&lt;18 years old"   "18-24 years old" "25-34 years old" "35-44 years old"
[5] "45-54 years old" "55-64 years old" "&gt;65 years old"  </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(data3<span class="sc">$</span>How.many.cups.of.coffee.do.you.typically.drink.per.day.)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Less than 1" "1"           "2"           "3"           "4"          
[6] "More than 4"</code></pre>
</div>
</div>
<p>Everything is in the order we want, now we can plot one more time, You will obtain the plots as below!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x =</span> data3<span class="sc">$</span>What.is.your.age., <span class="at">y =</span> data3<span class="sc">$</span>Count)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week5_1_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x =</span> data3<span class="sc">$</span>How.many.cups.of.coffee.do.you.typically.drink.per.day., <span class="at">y =</span> data3<span class="sc">$</span>Count)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week5_1_files/figure-html/unnamed-chunk-33-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The first plot shows that most of the participants are between 25 and 34 years old. The second plot indicates that most of the respondents drink between 1 and 2 cups of coffee everyday.</p>
<p>You might be curious whether there is an interaction, with older people drinking more coffee than younger people. In other words, you would need three variables in the codes… which is very difficult to do without other packages, espectially the “ggplot2” one! You can try by yourself!</p>
</section>
<section id="save-data-from-r-to-your-computer" class="level3" data-number="3.2.8">
<h3 data-number="3.2.8" class="anchored" data-anchor-id="save-data-from-r-to-your-computer"><span class="header-section-number">3.2.8</span> Save data from R to your computer</h3>
<p>For some reasons, we may want to save our data in the computer. But we are actually referring to two things at the same time:</p>
<ol type="1">
<li><p>Saving the R dataset, and</p></li>
<li><p>Exporting the R dataset such that we can open it with other programs.</p></li>
</ol>
<p>Both are doable, and let’s start with the first option with the code below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">save</span>(data3, <span class="at">file =</span> <span class="st">"data3.Rdata"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We just need the “save()” function, inside which we first tell R the dataset we want to save, and then the name of the file on the computer. We can choose the name of the file by ourself, as long as we do not forget the “.Rdata” extension. Once it is save, we can load the file later using the “load()” function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="at">file =</span> <span class="st">"data3.Rdata"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We may also want to save the data as a .csv file, readable by programs such as Excel. This is done with the code below:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span>(data3, <span class="st">"data3.csv"</span>, <span class="at">row.names =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s unpack it:</p>
<ul>
<li>We use the “<strong>write.csv</strong>” function, and we provide details inside the parentheses for:
<ul>
<li>The name of the dataset we want to export (here, <strong>data3</strong>),</li>
<li>The name we want it to have in our computer (here, <strong>data3.csv</strong>), and</li>
<li>the “<strong>row.names = FALSE</strong>” is here to say that we do not want the index of the rows. You can try and change to “TRUE” to see what happens.</li>
</ul></li>
</ul>
<p>It is also possible to export to .xlsx files, more directly readable by Excel, but this requires another library. We will encounter this in the rest of the tutorial.</p>
</section>
<section id="r-script-of-this-section" class="level3" data-number="3.2.9">
<h3 data-number="3.2.9" class="anchored" data-anchor-id="r-script-of-this-section"><span class="header-section-number">3.2.9</span> R script of this section</h3>
<p>You can find the R scripts including the codes presented in this section <a href="https://github.com/aymeric-collart/formosan-corpus-r/blob/master/assets/files/Script_Section1.2.R" target="_blank">here</a>. Don’t hesitate to use it and add comments for each line of code to make your own!</p>
</section>
</section>
<section id="common-mistakes-or-how-to-save-a-lot-of-time" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="common-mistakes-or-how-to-save-a-lot-of-time"><span class="header-section-number">3.3</span> Common mistakes, or how to save a lot of time</h2>
<p>You will run into many error messages, these intimidating red lines in the console block telling you that something wrong happened. We can spend hours trying to figure out what to do to make the codes work. Again, no worries! This is part of the learning process, and to be honest, even experts can’t avoid error messages. The most important thing is to learn from them, so that we are able to understand what the problem is, and how to solve it.</p>
<p>From my experience, there are mistakes we often make especially as first users of R. I remember that many students in the classes I attended and taught gave up on learning programming languages just because they had to spend too much time on debugging very basic mistakes, and they couldn’t focus on the opportunities R can offer. Below is a non-exhaustive list of such mistakes that I may update in the future.</p>
<section id="i-cant-load-the-data-from-my-computer" class="level3" data-number="3.3.1">
<h3 data-number="3.3.1" class="anchored" data-anchor-id="i-cant-load-the-data-from-my-computer"><span class="header-section-number">3.3.1</span> I can’t load the data from my computer</h3>
</section>
<section id="i-dont-have-any-error-message-but-my-code-wont-run" class="level3" data-number="3.3.2">
<h3 data-number="3.3.2" class="anchored" data-anchor-id="i-dont-have-any-error-message-but-my-code-wont-run"><span class="header-section-number">3.3.2</span> I don’t have any error message, but my code won’t run</h3>
</section>
<section id="variable-not-found-what-happened" class="level3" data-number="3.3.3">
<h3 data-number="3.3.3" class="anchored" data-anchor-id="variable-not-found-what-happened"><span class="header-section-number">3.3.3</span> “Variable not found”, what happened?</h3>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Copyright 2025, Aymeric Collart</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="https://bsky.app/profile/aymericcollart.bsky.social">
<p><iconify-icon role="img" inline="" icon="fa6-brands:bluesky" aria-label="Icon bluesky from fa6-brands Iconify.design set." title="Icon bluesky from fa6-brands Iconify.design set."></iconify-icon></p>
</a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/aymeric-collart">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>